FROM python:3.11-slim as builder
COPY . /app
WORKDIR /app
RUN pip install -r requirements-inference-service.txt
EXPOSE 5000
ENV PYTHONPATH /app
ENV FLASK_APP inference.py
CMD python -m flask run --host='0.0.0.0'
