FROM python:3.9.6-slim as builder
RUN apt-get update \
    && apt-get install -y gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY . /app
WORKDIR /app
RUN pip install --user -U pip \
    && pip install --user --no-cache-dir -r requirements-inference-service.txt

FROM python:3.9.6-slim as app
COPY --from=builder /root/.local /root/.local
COPY --from=builder /app /app
WORKDIR /app
ENV PATH=/root/.local/bin:$PATH
EXPOSE 5000
ENV PYTHONPATH /app
ENV FLASK_APP inference.py
CMD python -m flask run --host='0.0.0.0'
