FROM python:3.14-slim as builder
COPY . /app
WORKDIR /app
RUN pip install --no-deps formation_mlops_2-0.1.0-py3-none-any.whl
RUN pip install -r requirements-inference-service.txt
EXPOSE 5000
ENV PYTHONPATH /app
CMD uvicorn inference:app --host 0.0.0.0 --port 5000
