from config import TRAIN_DATA_PATH, FEATURES_PATH, MODEL_REGISTRY_FOLDER
from formation_indus_ds_avancee.feature_engineering import prepare_features
from formation_indus_ds_avancee.train_and_predict import train_model

prepare_features(TRAIN_DATA_PATH, FEATURES_PATH, training_mode=True)
train_model(FEATURES_PATH, MODEL_REGISTRY_FOLDER)
