name: Python package
on:
  push:
  pull_request:
    branches: [ dev ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --locked --all-groups
      - name: Run Linter
        run: uv run ruff check .
      - name: Run tests
        run: uv run pytest/test_unit
      - name: Run functional tests
        run: uv run behave tests/test_functional/features/
      - name: Run tests
        continue-on-error: true # Task is expected to fail (there is a test that trainee will fix"
        run: python -m pytest tests/test_architecture

